spring:
  datasource:
    url: 'jdbc:postgresql://192.168.50.90:5432/vissersuwald'
    username: sheepadmin
    password: Ih17j-konijnen
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
      default_schema: farming
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG