spring:
  datasource:
    url: 'jdbc:postgresql://192.168.178.185:5432/appsmith'
    username: postgres
    password: Ih10hawei
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
      default_schema: farming
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: QE7DXewpVO82rN331vhJD42qDVkVE1mT
            client-secret: CkOus7xto0EUVA4orwR_XSO_Rye6HdRIr5-G41Vmxhf2ovq2CNsJ3BkW_h9JRcEW
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://vissersuwald.eu.auth0.com/
server:
  port: 8443
  ssl:
    key-store: /etc/letsencrypt/live/backend.vissersuwald.nl/keystore.p12
    key-sore-password: Ih17j-konijnen
    keyStoreType: pkcs12
    keyAlias: tomcat
security:
  require-ssl: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG